imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: "@DdnetFoursquareBundle/Resources/config/config.yml" }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
#    assets_version: SomeVersionScheme
    session: ~
    default_locale:  %locale%

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: true
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
# only these lines are added additionally 
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                # make sure vendor library location is correct
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"        
            loggable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
            tree:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# FOS
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Ddnet\UserBundle\Entity\User

# JMS
jms_security_extra:
    # Whether you want to secure all services (true), or only secure specific
    # services (false); see also below
    secure_all_services: false

    # Enabling this setting will add an additional special attribute "IS_IDDQD".
    # Anybody with this attribute will effectively bypass all security checks.
    enable_iddqd_attribute: false

    # Enables expression language
    expressions: false

    # Allows you to disable some, or all built-in voters
    voters:
        disable_authenticated: false
        disable_role:          false
        disable_acl:           false

    # Allows you to specify access control rules for specific methods, such
    # as controller actions
    method_access_control: { }    
jms_aop:
    cache_dir: %kernel.cache_dir%/jms_aop  

ddnet_foursquare:
    api_key: WS4AWDPS5JYDZ3YLZMDBNNUJGTF2BADQD3PYMDXZSNWGLTQ5
    user_id: 421286
    
ivory_google_map:
    map:
      # map js prefix
      prefix_javascript_variable: "map_"
      # map contianer id
      html_container: "map"
      # async?
      async: false
      # auto zoom
      auto_zoom: false
      # map center - ignored if auto_zoom is enabled
      center:
          longitude:  0
          latitude:   0
          no_wrap:    true
      # default zoom - ignored if auto_zoom is enabled
      zoom: 3
      # map bounds - ignored if auto_zoom is disabled
      ## if bound extends overlays, coords of overlays are extended instead
      ## default: no bound
      bound:
          south_west:
              latitude:   -2.1
              longitude:  1.4
              no_wrap:    true
          north_east:
              latitude:   2.6
              longitude:  1.4
              no_wrap:    true
      # map type - hybrid, roadmap, satellite, terrain
      type: "roadmap" 
      # map width
      width:  "100%"
      # map height
      height: "100%"
      # map options
      map_options:
          disableDefaultUI:       true
          disableDoubleClickZoom: true
      # map stylesheet options
      stylesheet_options: 
          position: "absolute"
          top:      "32px"
          left:     "0px"
          z-index:  "-100"
      # google maps API language, default: en
      language: en
    geocoder:
      # geocoder class
      class: "Ivory\GoogleMapBundle\Model\Services\Geocoding\Geocoder"
      provider:
        # replaces REMOTE_ADDR value
        #fake_ip: "64.233.160.0"
        # provider class
        class: "Ivory\GoogleMapBundle\Model\Services\Geocoding\\Provider"
        # api key, deafult: no key
        api_key: ~
        # locale, default: no locale
        locale: en
      # adapter class
      adapter: "Geocoder\HttpAdapter\BuzzHttpAdapter"    
      
knp_last_tweets:
    fetcher:
        driver: api      
services:
 twig.extension.text:
     class: Twig_Extensions_Extension_Text
     tags:
         - { name: twig.extension }        