millwright_menu:
    renderers:
        navigation: #menu type id
            renderer: null # custom renderer
            rendererOptions:
                template: MillwrightMenuBundle:Default:knp_menu.html.twig
    items: #menu items
        home: #menu name, user for route name, if it not set in opts
            route: 'homepage'
            attributes:
                class: nav-link
        portfolio:
            attributes:
                class: nav-link
        contact:
            label: 'contact'
            route: 'contact'
            attributes:
                class: nav-link
        'by status':
            route: 'status'
            attributes:
                class: nav-link
        'by category':
            route: 'categories'
            attributes:
                class: nav-link
        'add a project':
            route: 'portfolio_new'
            roles: ROLE_ADMIN
            attributes:
                class: nav-link
        profile:          
            attributes:
                class: nav-link
        signout:
            route: 'fos_user_security_logout'
            roles: ROLE_USER
            attributes:
                class: nav-link
        signin:
            route: 'fos_user_security_login'
            attributes:
                class: nav-link
            roles: IS_AUTHENTICATED_ANONYMOUSLY
    tree:
        main:
            type: navigation # menu type id
            children:
                home: ~
                portfolio: 
                    children:
                          'by status': ~
                          'by category': ~
                          'add a project': ~
                contact: ~
                profile: ~
                