DdnetFoursquareBundle:
    resource: "@DdnetFoursquareBundle/Controller/"
    type:     annotation
    prefix:   /

DdnetUserBundle:
    resource: "@DdnetUserBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
portfolio_by_status:
    pattern:  /portfolio/status/{status}
    defaults: { _controller: DdnetPortfolioBundle:Project:index }
    requirements: 
      status:  "[\w-]+"
project_show:
    pattern:  /portfolio/{slug}
    defaults: { _controller: DdnetPortfolioBundle:Project:show }
    requirements: 
        slug:   "[\w-]+"      
homepage:
    pattern: /
    defaults: { _controller: DdnetPortfolioBundle:Project:index }
portfolio:
    pattern:  /portfolio
    defaults: { _controller: DdnetPortfolioBundle:Project:index }

blog:
    pattern: /blog
    defaults: { _controller: DdnetBlogBundle:Default:index }
profile:
    pattern: /profile
    defaults: { _controller: DdnetUserBundle:Profile:index }
contact:
    pattern: /contact
    defaults: { _controller: DdnetUtilityBundle:Default:contact }
    requirements: { _method: GET }

project_popup:
    pattern:  /portfolio/{id}
    defaults: { _controller: DdnetPortfolioBundle:Project:popup }
    requirements: 
        id:     \d+
project_new:
    pattern: /project/new
    defaults: { _controller: DdnetPortfolioBundle:Project:new }

        
client_new:
    pattern:  /clients/new
    defaults: { _controller: DdnetBillingBundle:Client:new }