0:
  image: 1f98fd9.jpg
  caption: wonky eyes.
  path_to: /bundles/ddnetuser/images/profile/
1:
  image: 4uqpfimpev_106078101-2.jpg
  caption:  sup?!
  path_to: /bundles/ddnetuser/mages/profile/
2:
  image: 2012-01-25-171419.jpg
  caption: livin' the life
  path_to: /bundles/ddnetuser/images/profile/
3:
  image: moxie.jpg
  caption: moxie at the beach
  path_to: /bundles/ddnetuser/images/profile/
4:
  image: me.jpg
  caption: halloween show
  path_to: /bundles/ddnetuser/images/profile/  
5:
  image: moxie_camp_smile.jpg
  caption: moxie enjoying the sun
  path_to: /bundles/ddnetuser/images/profile/  
6:
  image: rafting_7_2010.jpg
  caption: lunch rafting on the river
  path_to: /bundles/ddnetuser/images/profile/  
7:
  image: tat_sleeve.jpg
  caption: sleeve.
  path_to: /bundles/ddnetuser/images/profile/  